import Head from "next/head";
import Navbar from "components/Navbar/Navbar";
import { Inter } from "@next/font/google";
import BootstrapCarousel from "components/carousel/Bootstrap.js";
import Articles from "components/Nos_services/Articles";
import Footer from "components/Footer";
import Projets from "components/proj-main/projets";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Navbar />
          <BootstrapCarousel />
          <Articles />
          <Projets/>
          <Footer />
        </div>
      </main>
    </>
  );
}
